### ISSUE TITLE
Make "rebase.json" standalone ?

### ISSUE THREAD

**Issue by Zulko** [TeselaGen/ve_standalone#1]
Hi and thanks for the great open-source work.

I was looking for Javascript solution to find or filter out restriction enzymes based on user sequences (but not necessarily with an editor). I came across the "rebase.json" file in this repository, which stores information on many enzymes in a format which, if I understand correctly, is meant to be processed in the ve_sequence_utils module. As these enzymes infos could be really useful in many other projects I was wondering if you would consider releasing these as an npm module of its own. Would that make sense ?

Thanks in advance !

**Comment by tnrich** [comment]
@Zulko feel free to release that info as its own package! 

Just as a heads up, this particular repo isn't being maintained anymore, but ve-sequence-utils, ve-sequence-parsers (aka bio-parsers) and open-vector-editor are all being actively updated.

**Comment by Zulko** [comment]
Thanks very much!
